### ISSUE TITLE
What is downSamplePointMatrix?

### ISSUE THREAD

**Issue by raacampbell** [SainsburyWellcomeCentre/ara_tools#3]
I can't remember what downSamplePointMatrix is for. It seems useful but nothing calls it and it's use isn't documented. Figure this out!

**Comment by ablot** [comment]
It is supposed to be the downsampling function for a sparse point matrix. It could be used after clicking in Masiv to put the point in 25um voxel before calling `transformix` to throw them in the atlas (but I didn't try since I'm using some lasagna/python scripts to do that).
